language: cpp
os: linux
sudo: required
dist: trusty

compiler:
  - gcc
  - clang
    
before_script:
    - sudo apt-get install -y libboost1.55-all-dev libmysql++-dev libssl-dev cmake
    - ./tools/travis/installdeps.sh

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang

script:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    - $CXX --version
    - mkdir build && cd build
    - cmake ..
    - make

notifications:
   email:
     recipients:
       - sebastien.huss@gmail.com
     on_success: change
     on_failure: always
