language: cpp
os: linux
sudo: required
dist: trusty

compiler:
  - gcc

addons:
  apt:
    sources:
    - llvm-toolchain-precise
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.7
    - libboost1.55-all-dev
    - libmysql++-dev
    - libssl-dev
    - liblua5.2-dev
    - cmake
    - g++-5
    - gcc-5

before_script:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    - ./tools/travis/installdeps.sh

script:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    - $CXX --version
    - mkdir build && cd build
    - cmake ..
    - make

notifications:
   email:
     recipients:
       - sebastien.huss@gmail.com
     on_success: change
     on_failure: always
