language: cpp
os: linux

compiler:
  - gcc
  - clang
    
before_script:
    - sudo add-apt-repository ppa:apokluda/boost1.53 -y
    - sudo apt-get update -q
    - sudo apt-get install -y libboost1.53-all-dev
    - sudo apt-get install -y libmysql++-dev libssl-dev libjsoncpp-dev
    - sudo apt-get install cmake

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang

script:
    - $CXX --version
    - mkdir build && cd build
    - cmake ..
    - make

notifications:
   email:
     recipients:
       - sebastien.huss@gmail.com
     on_success: change
     on_failure: always
